# Generated by Django 4.1.7 on 2023-04-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='udpdated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='udpdated_at',
            new_name='updated_at',
        ),
    ]
